apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: my-applicationset
spec:
  generators:
  - pullRequest:
      github:
        owner: kesompochy
        repo: argocd-test
      requeueAfterSeconds: 300
  template:
    metadata:
      name: app-{{branch}}
    spec:
      source:
        repoURL: https://github.com/kesompochy/argocd-test.git
        targetRevision: main
        path: app
        kustomize:
          commonLabels:
            branch-name: "{{branch}}"
      project: default
      destination:
        server: https://kubernetes.default.svc
        namespace: test
      syncPolicy:
          automated:
            prune: true
