apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: app
    spec:
      containers:
      - name: nginx
        args:
        - nginx
        - -g
        - daemon off;
        image: nginx:1.21
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
          name: http-server
          protocol: TCP
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      - name: git-sync
        image: docker.git.pepabo.com/minne/minne-k8s/git-sync:v3.6.2
        env:
          - name: GIT_SYNC_REPO
            value: https://git.com/kesompochy/argocd-test.git
          - name: GIT_SYNC_BRANCH
            value: $(BRANCH_NAME)
          - name: GIT_SYNC_ROOT
            value: /sync
          - name: GIT_SYNC_DEST
            value: app
