
resources:
  - deployment.yaml

replacements:
  - source:
      kind: Deployment
      name: app
      fieldPath: metadata.labels.branch-name
    targets:
      - select:
          kind: Deployment
          name: app
        fieldPaths:
          - spec.template.spec.containers.[name=git-sync].env.[name=GIT_SYNC_BRANCH].value
  - source:
      kind: Deployment
      name: app
      fieldPath: metadata.labels.resource-name
    targets:
      - select:
          kind: Deployment
          name: app
        fieldPaths:
          - metadata.name
